token:
  header: Authorization
  schema: Bearer
  secretKey: banyuan
  expireSec: 3600

server:
  port: 8088

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cqmall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: banyuan
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

#redis
  redis:
    port: 6379
    host: localhost
    password: #
    database: 0
    timeout: 300ms


  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

#minio
minio:
  endPoint: http://192.168.43.182:9000
  bucketName: dev
  accessKey: banyuan
  secretKey: banyuan123
