spring:
  resources:
    static-locations: classpath:static/,file:static/
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
minio:
  endpoint: http://192.168.43.182:9000 #MinIO服务所在地址
  bucketName: dev #存储桶名称
  accessKey: banyuan #访问的key
  secretKey: banyuan123 #访问的秘钥
server:
  port: 8088
