POST http://localhost:8088/admin/login
Content-Type: application/json

//{"username":"productAdmin","password":"banyuan"}
{"username":"admin","password":"banyuan"}

> {% client.global.set("auth_token", response.body.data.token); %}
###

GET http://localhost:8088/admin/auth1
Authorization: BearereyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTU4NjQyMDIzMCwiZXhwIjoxNTg2NDIzODMwfQ.gF_2L-RjlbmpiX9YYcaBhL_e6sFopS2FWTIn5kOJ1aMxpiIZIJcWED0f4Hz6CcMzOIgba15-beYm965xypsM7A

###

GET http://localhost:8088/admin/auth2
Authorization: BearereyJhbGciOiJIUzUxMiJ9.eyJ1zdWIiOiJhZG1pbiIsImlhdCI6MTU4NjMxMzAxNCwiZXhwIjoxNTg2MzE2NjE0fQ.ZlxjrJiFZJOZJT7CkW1II8ATPsNgIW8wUthMYO9cwNzs2hVVYuIPH5m9Mi7UqtyQ0E_Cxl7ZJXpfRPDfUSF8gw

###



GET http://localhost:8088/product/list?pageNum=1&pageSize=5
Authorization: BearereyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTU4NjQyMDIzMCwiZXhwIjoxNTg2NDIzODMwfQ.gF_2L-RjlbmpiX9YYcaBhL_e6sFopS2FWTIn5kOJ1aMxpiIZIJcWED0f4Hz6CcMzOIgba15-beYm965xypsM7A

###


GET http://localhost:8088/order/list?pageNum=1&pageSize=10
Authorization: Bearer {{auth_token}}

###





